const en = {
  title: 'OCR & Editable PDF',
  description: 'Recognize text in images and scanned PDFs locally with PaddleOCR.js, correct every line, and export a searchable PDF without uploading your file.',
  tip: 'Recognize, review, preview, and export entirely in your browser', badge: 'PaddleOCR · Local processing',
  keywords: 'online OCR, PDF OCR, searchable PDF, image to text, local OCR, browser OCR, PaddleOCR.js, PP-OCRv5, editable PDF',
  cards: [['🔒','No file uploads','Your image, rendered PDF pages, and OCR text stay in browser memory.'],['✍️','Line-by-line editing','Use detected text boxes and confidence scores to review every OCR result.'],['📄','Searchable PDF','Rebuild visible text at its detected positions in a selectable, searchable PDF.']],
  introTitle: 'Browser OCR powered by PaddleOCR.js',
  intro: 'This tool uses the official @paddleocr/paddleocr-js SDK to run the PP-OCRv5 text detection and recognition pipeline in your browser. It accepts an image or scanned PDF, finds text regions, recognizes each line, and lets you correct the result before creating a PDF.',
  techTitle: 'How local OCR works',
  tech: [['PP-OCRv5 pipeline','PaddleOCR.js combines text detection and text recognition. Each result includes the recognized text, polygon coordinates, and a confidence score.'],['WASM inference','The SDK manages OpenCV.js and ONNX Runtime. Inference runs through WebAssembly on your device without sending document pixels to an OCR server.'],['Model caching','The OCR model and WASM runtime are downloaded on first use and can be cached by the browser. Later runs are usually faster.'],['Private document workflow','Only public model and runtime resources are downloaded. Your selected file and corrected text are never uploaded by this tool.']],
  howTitle: 'Convert a scan into a searchable PDF',
  steps: [['1','Choose one file','Open a JPG, PNG, WebP, BMP, or scanned PDF.'],['2','Automatic OCR','The file is rendered locally and recognition starts automatically.'],['3','Review the text','Edit any detected line in the page overlay or full-text view.'],['4','Export PDF','Download a clean PDF that reconstructs visible text using the detected layout.']],
  faqTitle: 'OCR and searchable PDF FAQ',
  faqs: [['Does ShotEasy upload my document?','No. Document images, PDF pages, and recognized text remain in your browser. The browser only downloads the public OCR model, WASM runtime, and export font when needed.'],['Why is the first OCR run slower?','The first run initializes OpenCV.js and ONNX Runtime and downloads the PP-OCRv5 model. Browser caching can make later recognition faster.'],['Can I correct recognition mistakes?','Yes. Every detected text line is editable. You can edit it over the page or use the full-text panel before exporting.'],['What makes the exported PDF searchable?','ShotEasy writes corrected OCR lines as visible PDF text at their detected positions. The source image is not embedded, so compatible PDF viewers can search and select the reconstructed content.']],
};

const translations = {
  'en': en,
  'en-in': { ...en, description: 'Recognise text in images and scanned PDFs locally with PaddleOCR.js, correct every line, and export a searchable PDF without uploading your file.', tip: 'Recognise, review, preview, and export entirely in your browser' },
  'zh-CN': {
    title:'OCR 文字识别与 PDF 编辑器', description:'使用 PaddleOCR.js 在浏览器本地识别图片和扫描 PDF，逐行校对文字并导出可搜索 PDF，文件无需上传。', tip:'识别、校对、预览、导出，全程只在你的浏览器中完成', badge:'PaddleOCR · 本地处理', keywords:'在线OCR, PDF OCR, 可搜索PDF, 图片转文字, 本地OCR, 浏览器OCR, PaddleOCR.js, PP-OCRv5, PDF编辑器',
    cards:[['🔒','文件不上传','图片、PDF 页面和识别文字仅保存在当前浏览器内存中。'],['✍️','逐行校对','结合检测框和置信度检查并修改每一行识别结果。'],['📄','可搜索 PDF','按 OCR 检测位置重建可见文字，导出可选择、可搜索的 PDF。']],
    introTitle:'由 PaddleOCR.js 驱动的浏览器 OCR', intro:'本工具使用官方 @paddleocr/paddleocr-js SDK，在浏览器中运行 PP-OCRv5 文字检测与识别产线。导入图片或扫描 PDF 后，它会定位文字区域、识别每一行，并允许你在生成 PDF 前修正结果。',
    techTitle:'本地 OCR 如何工作', tech:[['PP-OCRv5 识别产线','PaddleOCR.js 组合文字检测与文字识别，结果包含文本、文字框多边形坐标和置信度。'],['WASM 本地推理','SDK 内部管理 OpenCV.js 与 ONNX Runtime，通过 WebAssembly 在设备上推理，无需把文档像素发送给 OCR 服务器。'],['模型浏览器缓存','首次使用会下载 OCR 模型与 WASM 运行资源，浏览器缓存后再次识别通常更快。'],['隐私文档流程','工具只下载公开模型和运行资源，你选择的文件与修改后的文字不会被上传。']],
    howTitle:'把扫描件转换为可搜索 PDF', steps:[['1','选择一个文件','打开 JPG、PNG、WebP、BMP 或扫描 PDF。'],['2','自动开始 OCR','文件在本地完成解析，随后自动识别文字。'],['3','检查与校对','在页面文字框或全文视图中修改识别结果。'],['4','导出 PDF','按检测到的版面位置重建文字，下载不含原图的可搜索 PDF。']],
    faqTitle:'OCR 与可搜索 PDF 常见问题', faqs:[['ShotEasy 会上传我的文档吗？','不会。文档图片、PDF 页面和识别文字都留在浏览器中；仅在需要时下载公开 OCR 模型、WASM 运行资源和导出字体。'],['为什么第一次 OCR 比较慢？','首次运行需要初始化 OpenCV.js 与 ONNX Runtime，并下载 PP-OCRv5 模型；缓存完成后再次识别通常更快。'],['识别错误可以修改吗？','可以。每个检测到的文字行都能编辑，可直接在页面上修改，也可使用全文编辑视图。'],['导出的 PDF 为什么可以搜索？','ShotEasy 把校对后的 OCR 文字按检测位置写成可见 PDF 文本，不嵌入原图，因此可在兼容的 PDF 阅读器中搜索和选择。']],
  },
  'pt-br': {
    title:'OCR e PDF editável', description:'Reconheça texto em imagens e PDFs digitalizados localmente com PaddleOCR.js, corrija cada linha e exporte um PDF pesquisável sem enviar o arquivo.', tip:'Reconheça, revise, visualize e exporte diretamente no navegador', badge:'PaddleOCR · Processamento local', keywords:'OCR online, OCR PDF, PDF pesquisável, imagem para texto, OCR local, PaddleOCR.js, PP-OCRv5',
    cards:[['🔒','Sem upload de arquivos','Imagens, páginas renderizadas e texto OCR permanecem na memória do navegador.'],['✍️','Edição linha por linha','Revise o texto usando caixas detectadas e pontuações de confiança.'],['📄','PDF pesquisável','Preserve a aparência original com uma camada de texto selecionável.']], introTitle:'OCR no navegador com PaddleOCR.js', intro:'A ferramenta usa o SDK oficial @paddleocr/paddleocr-js para executar detecção e reconhecimento PP-OCRv5 no navegador. Ela localiza regiões de texto e permite corrigi-las antes de criar o PDF.', techTitle:'Como funciona o OCR local', tech:[['Pipeline PP-OCRv5','O resultado inclui texto, coordenadas poligonais e pontuação de confiança.'],['Inferência WASM','OpenCV.js e ONNX Runtime executam no seu dispositivo via WebAssembly.'],['Cache do modelo','O modelo e o runtime são baixados no primeiro uso e podem ficar em cache.'],['Fluxo privado','Somente recursos públicos são baixados; seu documento não é enviado.']], howTitle:'Transforme uma digitalização em PDF pesquisável', steps:[['1','Escolha um arquivo','Abra JPG, PNG, WebP, BMP ou PDF digitalizado.'],['2','OCR automático','O reconhecimento começa após o processamento local.'],['3','Revise o texto','Corrija linhas na página ou na visualização de texto.'],['4','Exporte o PDF','Baixe o PDF com camada de texto pesquisável.']], faqTitle:'Perguntas sobre OCR e PDF', faqs:[['Meu documento é enviado?','Não. O documento e o texto reconhecido permanecem no navegador.'],['Por que a primeira execução demora?','O navegador precisa baixar e iniciar o modelo PP-OCRv5 e o runtime WASM.'],['Posso corrigir erros?','Sim. Todas as linhas detectadas são editáveis antes da exportação.'],['Como o PDF se torna pesquisável?','Uma camada de texto corrigido é posicionada sobre a página digitalizada.']],
  },
  'es': {
    title:'OCR y PDF editable', description:'Reconoce texto en imágenes y PDF escaneados localmente con PaddleOCR.js, corrige cada línea y exporta un PDF buscable sin subir el archivo.', tip:'Reconoce, revisa, previsualiza y exporta en tu navegador', badge:'PaddleOCR · Procesamiento local', keywords:'OCR online, OCR PDF, PDF buscable, imagen a texto, OCR local, PaddleOCR.js, PP-OCRv5',
    cards:[['🔒','Sin subir archivos','Las imágenes, páginas y texto OCR permanecen en la memoria del navegador.'],['✍️','Edición línea por línea','Revisa cada resultado mediante cajas detectadas y puntuaciones de confianza.'],['📄','PDF buscable','Conserva la página original y añade una capa de texto seleccionable.']], introTitle:'OCR en el navegador con PaddleOCR.js', intro:'Esta herramienta usa el SDK oficial @paddleocr/paddleocr-js para ejecutar la detección y el reconocimiento PP-OCRv5 en el navegador. Localiza líneas de texto y permite corregirlas antes de crear el PDF.', techTitle:'Cómo funciona el OCR local', tech:[['Flujo PP-OCRv5','Cada resultado incluye texto, coordenadas poligonales y confianza.'],['Inferencia WASM','OpenCV.js y ONNX Runtime funcionan mediante WebAssembly en tu dispositivo.'],['Caché del modelo','El modelo se descarga la primera vez y el navegador puede guardarlo.'],['Flujo privado','Solo se descargan recursos públicos; tu documento no se envía.']], howTitle:'Convierte un escaneo en PDF buscable', steps:[['1','Elige un archivo','Abre JPG, PNG, WebP, BMP o un PDF escaneado.'],['2','OCR automático','El reconocimiento comienza después del procesamiento local.'],['3','Revisa el texto','Corrige líneas sobre la página o en la vista completa.'],['4','Exporta el PDF','Descarga un PDF con una capa de texto buscable.']], faqTitle:'Preguntas sobre OCR y PDF', faqs:[['¿Se sube mi documento?','No. El documento y el texto reconocido permanecen en tu navegador.'],['¿Por qué tarda la primera vez?','Se descargan e inicializan el modelo PP-OCRv5 y el entorno WASM.'],['¿Puedo corregir errores?','Sí. Puedes editar todas las líneas antes de exportar.'],['¿Cómo se puede buscar en el PDF?','Se coloca una capa con el texto corregido sobre la página escaneada.']],
  },
};

const compact = {
  fr:['OCR et PDF modifiable','Reconnaissez localement le texte des images et PDF numérisés avec PaddleOCR.js, corrigez-le puis exportez un PDF consultable sans téléverser le fichier.','Reconnaître, vérifier et exporter dans votre navigateur','Traitement local','Aucun fichier envoyé','Correction ligne par ligne','PDF consultable','OCR dans le navigateur avec PaddleOCR.js','Comment fonctionne l’OCR local','Transformer un scan en PDF consultable','Questions sur l’OCR et les PDF'],
  de:['OCR und bearbeitbares PDF','Erkennen Sie Text in Bildern und gescannten PDFs lokal mit PaddleOCR.js, korrigieren Sie ihn und exportieren Sie ein durchsuchbares PDF ohne Upload.','Erkennen, prüfen und exportieren – direkt im Browser','Lokale Verarbeitung','Keine Datei-Uploads','Zeilenweise bearbeiten','Durchsuchbares PDF','Browser-OCR mit PaddleOCR.js','So funktioniert lokales OCR','Scan in durchsuchbares PDF umwandeln','Fragen zu OCR und PDF'],
  ja:['OCR・編集可能なPDF','PaddleOCR.jsを使って画像やスキャンPDFをブラウザ内で文字認識し、修正して検索可能なPDFとして保存できます。ファイルはアップロードされません。','認識・確認・編集・書き出しをブラウザ内で完結','ローカル処理','ファイルをアップロードしない','行ごとに編集','検索可能なPDF','PaddleOCR.jsによるブラウザOCR','ローカルOCRの仕組み','スキャンを検索可能なPDFに変換','OCRとPDFのよくある質問'],
  hi:['OCR और संपादन योग्य PDF','PaddleOCR.js से चित्रों और स्कैन PDF का टेक्स्ट ब्राउज़र में पहचानें, सुधारें और फ़ाइल अपलोड किए बिना खोज योग्य PDF बनाएँ।','पहचान, समीक्षा और निर्यात पूरी तरह ब्राउज़र में','स्थानीय प्रोसेसिंग','फ़ाइल अपलोड नहीं','हर पंक्ति संपादित करें','खोज योग्य PDF','PaddleOCR.js द्वारा ब्राउज़र OCR','स्थानीय OCR कैसे काम करता है','स्कैन को खोज योग्य PDF बनाएँ','OCR और PDF के प्रश्न'],
  ko:['OCR 및 편집 가능한 PDF','PaddleOCR.js로 이미지와 스캔 PDF의 텍스트를 브라우저에서 인식하고 수정한 뒤 파일 업로드 없이 검색 가능한 PDF로 저장하세요.','인식, 검토, 편집, 내보내기를 브라우저에서 완료','로컬 처리','파일 업로드 없음','줄별 편집','검색 가능한 PDF','PaddleOCR.js 기반 브라우저 OCR','로컬 OCR 작동 방식','스캔을 검색 가능한 PDF로 변환','OCR 및 PDF 자주 묻는 질문'],
  id:['OCR & PDF yang dapat diedit','Kenali teks pada gambar dan PDF pindaian secara lokal dengan PaddleOCR.js, koreksi, lalu ekspor PDF yang dapat dicari tanpa mengunggah file.','Kenali, tinjau, dan ekspor langsung di browser','Pemrosesan lokal','Tanpa unggah file','Edit per baris','PDF dapat dicari','OCR browser dengan PaddleOCR.js','Cara kerja OCR lokal','Ubah pindaian menjadi PDF yang dapat dicari','Tanya jawab OCR dan PDF'],
  vn:['OCR & PDF có thể chỉnh sửa','Nhận dạng văn bản trong ảnh và PDF quét ngay trên trình duyệt bằng PaddleOCR.js, sửa từng dòng và xuất PDF có thể tìm kiếm mà không tải tệp lên.','Nhận dạng, kiểm tra và xuất hoàn toàn trong trình duyệt','Xử lý cục bộ','Không tải tệp lên','Sửa theo từng dòng','PDF có thể tìm kiếm','OCR trình duyệt với PaddleOCR.js','OCR cục bộ hoạt động thế nào','Chuyển bản quét thành PDF tìm kiếm được','Câu hỏi về OCR và PDF'],
  uk:['OCR і редагований PDF','Розпізнавайте текст у зображеннях і сканованих PDF локально через PaddleOCR.js, виправляйте його та експортуйте PDF із пошуком без завантаження файла.','Розпізнавання, перевірка й експорт у браузері','Локальна обробка','Без завантаження файлів','Порядкове редагування','PDF із пошуком','Браузерний OCR на PaddleOCR.js','Як працює локальний OCR','Перетворіть скан у PDF із пошуком','Питання про OCR і PDF'],
  ru:['OCR и редактируемый PDF','Распознавайте текст в изображениях и сканированных PDF локально с PaddleOCR.js, исправляйте его и экспортируйте PDF с поиском без загрузки файла.','Распознавание, проверка и экспорт прямо в браузере','Локальная обработка','Без загрузки файлов','Построчное редактирование','PDF с поиском','Браузерный OCR на PaddleOCR.js','Как работает локальный OCR','Преобразуйте скан в PDF с поиском','Вопросы об OCR и PDF'],
};

const compactDetails = {
  fr:['Les images, pages PDF et textes reconnus restent dans la mémoire du navigateur.','Modifiez chaque ligne détectée avant l’exportation.','Conservez le scan avec une couche de texte sélectionnable.','Le SDK officiel exécute la détection et la reconnaissance PP-OCRv5 directement dans le navigateur.','Chaque résultat contient le texte, ses coordonnées et un score de confiance.','OpenCV.js et ONNX Runtime exécutent le modèle via WebAssembly sur votre appareil.','Le modèle est téléchargé au premier usage puis peut être mis en cache.','Seules les ressources publiques du modèle sont téléchargées; votre document n’est pas envoyé.','Choisir un fichier','L’OCR démarre automatiquement','Vérifier le texte','Exporter le PDF','Mon document est-il téléversé ?','Pourquoi le premier OCR est-il plus lent ?','Puis-je corriger le texte ?','Pourquoi le PDF est-il consultable ?'],
  de:['Bilder, PDF-Seiten und erkannter Text bleiben im Browserspeicher.','Bearbeiten Sie jede erkannte Zeile vor dem Export.','Das Scanbild bleibt erhalten und erhält eine auswählbare Textebene.','Das offizielle SDK führt PP-OCRv5-Texterkennung direkt im Browser aus.','Jedes Ergebnis enthält Text, Polygonkoordinaten und einen Konfidenzwert.','OpenCV.js und ONNX Runtime führen das Modell per WebAssembly auf Ihrem Gerät aus.','Modell und Laufzeit werden beim ersten Start geladen und können zwischengespeichert werden.','Nur öffentliche Modellressourcen werden geladen; Ihr Dokument wird nicht übertragen.','Datei auswählen','OCR startet automatisch','Text prüfen','PDF exportieren','Wird mein Dokument hochgeladen?','Warum dauert der erste Lauf länger?','Kann ich Erkennungsfehler korrigieren?','Warum ist das PDF durchsuchbar?'],
  ja:['画像、PDFページ、認識結果はブラウザのメモリ内に保持されます。','書き出す前に検出された各行を編集できます。','元のスキャン画像を保ち、選択可能な文字レイヤーを追加します。','公式SDKがPP-OCRv5の文字検出と認識をブラウザ内で実行します。','結果には文字、ポリゴン座標、信頼度が含まれます。','OpenCV.jsとONNX RuntimeがWebAssembly経由で端末上の推論を行います。','初回にモデルをダウンロードし、ブラウザにキャッシュできます。','公開モデルだけを取得し、文書データは送信しません。','ファイルを選択','OCRを自動開始','文字を確認','PDFを書き出す','文書はアップロードされますか？','初回のOCRが遅いのはなぜですか？','認識ミスを修正できますか？','PDFを検索できる仕組みは？'],
  hi:['चित्र, PDF पृष्ठ और पहचाना गया टेक्स्ट ब्राउज़र मेमोरी में रहता है।','निर्यात से पहले हर पहचानी गई पंक्ति संपादित करें।','मूल स्कैन के साथ चुनने योग्य टेक्स्ट परत जोड़ें।','आधिकारिक SDK ब्राउज़र में PP-OCRv5 टेक्स्ट पहचान चलाता है।','हर परिणाम में टेक्स्ट, बहुभुज निर्देशांक और विश्वास स्कोर होता है।','OpenCV.js और ONNX Runtime WebAssembly के माध्यम से आपके उपकरण पर चलते हैं।','मॉडल पहली बार डाउनलोड होता है और ब्राउज़र में कैश हो सकता है।','केवल सार्वजनिक मॉडल संसाधन डाउनलोड होते हैं; दस्तावेज़ भेजा नहीं जाता।','फ़ाइल चुनें','OCR अपने आप शुरू होता है','टेक्स्ट जाँचें','PDF निर्यात करें','क्या मेरा दस्तावेज़ अपलोड होता है?','पहला OCR धीमा क्यों है?','क्या पहचान की गलती सुधार सकता हूँ?','PDF खोज योग्य कैसे बनता है?'],
  ko:['이미지, PDF 페이지와 인식 텍스트는 브라우저 메모리에만 남습니다.','내보내기 전에 감지된 각 줄을 수정할 수 있습니다.','원본 스캔 위에 선택 가능한 텍스트 레이어를 추가합니다.','공식 SDK가 브라우저에서 PP-OCRv5 텍스트 감지와 인식을 실행합니다.','결과에는 텍스트, 다각형 좌표와 신뢰도 점수가 포함됩니다.','OpenCV.js와 ONNX Runtime이 WebAssembly를 통해 기기에서 실행됩니다.','첫 실행 시 모델을 다운로드하며 브라우저가 캐시할 수 있습니다.','공개 모델 리소스만 내려받고 문서는 전송하지 않습니다.','파일 선택','OCR 자동 시작','텍스트 검토','PDF 내보내기','문서가 업로드되나요?','첫 OCR이 느린 이유는 무엇인가요?','인식 오류를 수정할 수 있나요?','PDF를 검색할 수 있는 이유는 무엇인가요?'],
  id:['Gambar, halaman PDF, dan teks OCR tetap berada di memori browser.','Edit setiap baris yang terdeteksi sebelum mengekspor.','Pertahankan tampilan pindaian dengan lapisan teks yang dapat dipilih.','SDK resmi menjalankan deteksi dan pengenalan PP-OCRv5 langsung di browser.','Setiap hasil berisi teks, koordinat poligon, dan skor keyakinan.','OpenCV.js dan ONNX Runtime menjalankan model melalui WebAssembly di perangkat Anda.','Model diunduh saat penggunaan pertama dan dapat disimpan dalam cache browser.','Hanya sumber daya model publik yang diunduh; dokumen tidak dikirim.','Pilih file','OCR dimulai otomatis','Tinjau teks','Ekspor PDF','Apakah dokumen saya diunggah?','Mengapa OCR pertama lebih lambat?','Dapatkah kesalahan diperbaiki?','Bagaimana PDF menjadi dapat dicari?'],
  vn:['Hình ảnh, trang PDF và văn bản OCR chỉ nằm trong bộ nhớ trình duyệt.','Chỉnh sửa từng dòng được phát hiện trước khi xuất.','Giữ nguyên bản quét và thêm lớp văn bản có thể chọn.','SDK chính thức chạy nhận dạng PP-OCRv5 trực tiếp trong trình duyệt.','Mỗi kết quả gồm văn bản, tọa độ đa giác và điểm tin cậy.','OpenCV.js và ONNX Runtime chạy mô hình qua WebAssembly trên thiết bị.','Mô hình được tải ở lần đầu và có thể được trình duyệt lưu đệm.','Chỉ tài nguyên mô hình công khai được tải xuống; tài liệu không được gửi đi.','Chọn tệp','OCR tự động bắt đầu','Kiểm tra văn bản','Xuất PDF','Tài liệu có bị tải lên không?','Tại sao lần OCR đầu chậm hơn?','Có thể sửa lỗi nhận dạng không?','PDF có thể tìm kiếm bằng cách nào?'],
  uk:['Зображення, сторінки PDF і розпізнаний текст залишаються в пам’яті браузера.','Редагуйте кожен знайдений рядок перед експортом.','Збережіть вигляд скана й додайте текстовий шар для виділення.','Офіційний SDK запускає розпізнавання PP-OCRv5 безпосередньо в браузері.','Результат містить текст, координати полігона та оцінку впевненості.','OpenCV.js і ONNX Runtime працюють через WebAssembly на вашому пристрої.','Модель завантажується під час першого запуску й може кешуватися.','Завантажуються лише публічні ресурси моделі; документ не надсилається.','Виберіть файл','OCR запускається автоматично','Перевірте текст','Експортуйте PDF','Чи завантажується мій документ?','Чому перший OCR повільніший?','Чи можна виправити помилки?','Як PDF стає доступним для пошуку?'],
  ru:['Изображение, страницы PDF и распознанный текст остаются в памяти браузера.','Редактируйте каждую найденную строку перед экспортом.','Сохраните вид скана и добавьте выделяемый текстовый слой.','Официальный SDK запускает распознавание PP-OCRv5 прямо в браузере.','Результат содержит текст, координаты полигона и оценку уверенности.','OpenCV.js и ONNX Runtime работают через WebAssembly на вашем устройстве.','Модель загружается при первом запуске и может кэшироваться браузером.','Загружаются только публичные ресурсы модели; документ не отправляется.','Выберите файл','OCR запускается автоматически','Проверьте текст','Экспортируйте PDF','Загружается ли мой документ?','Почему первый OCR работает медленнее?','Можно ли исправить ошибки?','Как PDF становится доступным для поиска?'],
};

Object.entries(compact).forEach(([locale, v]) => {
  const d = compactDetails[locale];
  translations[locale] = {
    ...en, title:v[0], description:v[1], tip:v[2], badge:`PaddleOCR · ${v[3]}`,
    keywords:`OCR, PDF OCR, ${v[0]}, PaddleOCR.js, PP-OCRv5`,
    cards:[['🔒',v[4],d[0]],['✍️',v[5],d[1]],['📄',v[6],d[2]]],
    introTitle:v[7], intro:d[3], techTitle:v[8],
    tech:[['PP-OCRv5',d[4]],['WebAssembly',d[5]],[v[3],d[6]],[v[4],d[7]]],
    howTitle:v[9], steps:[['1',d[8],d[0]],['2',d[9],d[3]],['3',d[10],d[1]],['4',d[11],d[2]]],
    faqTitle:v[10], faqs:[[d[12],d[7]],[d[13],d[6]],[d[14],d[1]],[d[15],d[2]]],
  };
});

export const getOcrCopy = (locale = 'en') => translations[locale] || en;
